name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag marques576/opentourney-frontend:latest
           
    - name: Docker Push
      run: docker push marques576/opentourney-frontend:latest
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 cloudv2

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl delete -f $GITHUB_WORKSPACE/config/frontend-deployment.yaml

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/config/frontend-deployment.yaml

    - name: Verify deployment
      run: kubectl rollout status deployment/frontend
      
    - name: Send Discord Webhook
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" -X POST -d '{"content": "Frontend Server Deployed :white_check_mark:"}' $DISCORD_WEBHOOK_URL
